# Basics 

This guide was almost completely adapted from the great 
[NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html) tutorial. You can also check out 
[this other guide with more illustrations](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d).

NumPy (**Num**erical **Py**thon) is an open source Python library that's
widely used in science and engineering. The NumPy library contains
multidimensional array data structures, such as the homogeneous,
N-dimensional `ndarray`, and a large library of functions that operate
efficiently on these data structures. 

## How to import NumPy

After [installing NumPy](https://numpy.org/install/), it may be imported
into Python code like:



In [2]:
import numpy as np

This widespread convention allows access to NumPy features with a short,
recognizable prefix (`np.`) while distinguishing NumPy features from
others that have the same name.

## Why use NumPy?

Python lists are excellent, general-purpose containers. They can be
"heterogeneous", meaning that they can contain elements of a variety of
types, and they are quite fast when used to perform individual
operations on a handful of elements.

Depending on the characteristics of the data and the types of operations
that need to be performed, other containers may be more appropriate; by
exploiting these characteristics, we can improve speed, reduce memory
consumption, and offer a high-level syntax for performing a variety of
common processing tasks. NumPy shines when there are large quantities of
"homogeneous" (same-type) data to be processed on the CPU.

To illustrate the performance boost NumPy can offer, we perform the same operations, first in pure Python, then using NumPy, and time both of them:

In [ ]:
%%time
li = [i for i in range(1000000)]
list_sum = sum(li)

CPU times: user 18.2 ms, sys: 8.55 ms, total: 26.7 ms
Wall time: 26.3 ms


In [ ]:
%%time
arr = np.arange(1000000)
arr_sum = np.sum(arr)

CPU times: user 2.86 ms, sys: 2.28 ms, total: 5.14 ms
Wall time: 3.34 ms


```{tip}
Note the use of the `%%time` cell magic, it is very useful to compare the performance of two pieces of code!
```

## What is an "array"?

In computer programming, an array is a structure for storing and
retrieving data. We often talk about an array as if it were a grid in
space, with each cell storing one element of the data. For instance, if
each element of the data were a number, we might visualize a
"one-dimensional" array like a list:

$$\begin{aligned}
\begin{array}{|c||c|c|c|}
\hline
1 & 5 & 2 & 0 \\
\hline
\end{array}
\end{aligned}$$

A two-dimensional array would be like a table:

$$\begin{aligned}
\begin{array}{|c||c|c|c|}
\hline
1 & 5 & 2 & 0 \\
\hline
8 & 3 & 6 & 1 \\
\hline
1 & 7 & 2 & 9 \\
\hline
\end{array}
\end{aligned}$$

A three-dimensional array would be like a set of tables, perhaps stacked
as though they were printed on separate pages. In NumPy, this idea is
generalized to an arbitrary number of dimensions, and so the fundamental
array class is called `ndarray`: it represents an "N-dimensional array".

Most NumPy arrays have some restrictions. For instance:

-   All elements of the array must be of the same type of data.
-   Once created, the total size of the array can't change.
-   The shape must be "rectangular", not "jagged"; e.g., each row of a
    two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to
make the array faster, more memory efficient, and more convenient to use
than less restrictive data structures.

For the remainder of this document, we will use the word "array" to
refer to an instance of `ndarray`.

## Array fundamentals

One way to initialize an array is using a Python sequence, such as a
list. For example:

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

Elements of an array can be accessed in various ways. For instance, we can
access an individual element of this array as we would access an element
in the original list: using the integer index of the element within
square brackets.

In [6]:
a[0]

1

```{note}
As with built-in Python sequences, NumPy arrays are "0-indexed": the
first element of the array is accessed using index `0`, not `1`.
```

Like the original list, the array is mutable.

In [7]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

Also like the original list, Python slice notation can be used for
indexing.

In [8]:
a[:3]

array([10,  2,  3])

One major difference is that slice indexing of a list copies the
elements into a new list, but slicing an array returns a *view*: an
object that refers to the data in the original array. The original array
can be mutated using the view.

In [9]:
b = a[3:]
b

array([4, 5, 6])

In [10]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

Two- and higher-dimensional arrays can be initialized from nested Python
sequences:

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In NumPy, a dimension of an array is sometimes referred to as an "axis".
This terminology may be useful to disambiguate between the
dimensionality of an array and the dimensionality of the data
represented by the array. For instance, the array `a` could represent
three points, each lying within a four-dimensional space, but `a` has
only two "axes".

Another difference between an array and a list of lists is that an
element of the array can be accessed by specifying the index along each
axis within a *single* set of square brackets, separated by commas. For
instance, the element `8` is in row `1` and column `3`:

In [12]:
a[1, 3]

8

```{note}
You might hear of a 0-D (zero-dimensional) array referred to as a
"scalar", a 1-D (one-dimensional) array as a "vector", a 2-D
(two-dimensional) array as a "matrix", or an N-D (N-dimensional, where
"N" is typically an integer greater than 2) array as a "tensor". For
clarity, it is best to avoid the mathematical terms when referring to an
array because the mathematical objects with these names behave
differently than arrays (e.g. "matrix" multiplication is fundamentally
different from "array" multiplication), and there are other objects in
the scientific Python ecosystem that have these names (e.g. the
fundamental data structure of PyTorch is the "tensor").
```

## Array attributes

The number of dimensions of an array is contained in the `ndim`
attribute.

In [13]:
a.ndim

2

The shape of an array is a tuple of non-negative integers that specify
the number of elements along each dimension.

In [14]:
a.shape

(3, 4)

The fixed, total number of elements in array is contained in the `size`
attribute.

In [15]:
a.size

12


Arrays are typically "homogeneous", meaning that they contain elements
of only one "data type". The data type is recorded in the `dtype`
attribute.

In [16]:
a.dtype

dtype('int64')

## How to create a basic array

Besides creating an array from a sequence of elements, you can easily
create an array filled with `0`'s:

In [17]:
np.zeros(2)

array([0., 0.])

Or an array filled with `1`'s:

In [18]:
np.ones(2)

array([1., 1.])

While the default data type is floating point (`np.float64`), you can
explicitly specify which data type you want using the `dtype` keyword. :

In [19]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

You can also create an array filled with a specific value, using `np.full()`:

In [20]:
np.full((2, 3), 42)

array([[42, 42, 42],
       [42, 42, 42]])

You can also create an array with a range of elements:

In [21]:
np.arange(4)

array([0, 1, 2, 3])

And even an array that contains a range of evenly spaced intervals. To
do this, you will specify the **first number**, **last number**, and the
**step size**. :

In [22]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

**Exercise**: how would you create the equivalent list, in a single line?

In [23]:
# Instead of creation an a(rray)range, simply create a list from a range!
list(range(2, 9, 2))

[2, 4, 6, 8]

You can also use `np.linspace()` to create an array with `num` values
spaced linearly in a specified interval:

In [24]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Basic array operations

Once you've created your arrays, you can start to work with them. Let's
say, for example, that you've created two arrays, one called "data" and
one called "ones"

![image](img/np_array_dataones.png)

You can add the arrays together with the plus sign.

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

![image](img/np_data_plus_ones.png)

You can, of course, do more than just addition!

In [ ]:
data - ones, data * data, data / data

(array([0, 1]), array([1, 4]), array([1., 1.]))

![image](img/np_sub_mult_divide.png)

## How to create an array from existing data

You can easily create a new array from a section of an existing array.

Let's say you have this array:

In [123]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

You can concatenate it to another, to add new entries:

In [125]:
np.concatenate([a, np.array([11, 12])])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

You can stack two existing arrays, both vertically and
horizontally. Let's say you have two arrays, `a1` and `a2`:

In [27]:
a1 = np.array(
    [
        [1, 1],
        [2, 2],
    ]
)
a2 = np.array(
    [
        [3, 3],
        [4, 4],
    ]
)

You can stack them vertically with `vstack`:

In [28]:
np.vstack([a1, a2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

or, equivalently, concatenating them together along the rows, by passing `axis=0` to `np.concatenate()`:

In [29]:
np.concatenate([a1, a2], axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Or stack them horizontally with `hstack`:

In [30]:
np.hstack([a1, a2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

or, again, equivalently, concatenating them together along the columns, by passing `axis=1` to `np.concatenate()`:

In [31]:
np.concatenate([a1, a2], axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Transposing and reshaping a matrix

In [ ]:
data = np.arange(1, 7)

You may also need to switch the dimensions of a matrix. This can happen
when, for example, you have a model that expects a certain input shape
that is different from your dataset. This is where the `reshape` method
can be useful. You simply need to pass in the new dimensions that you
want for the matrix. :

In [ ]:
data = data.reshape((2, 3))
data

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data = data.reshape((3, 2))
data

array([[1, 2],
       [3, 4],
       [5, 6]])

![image](img/np_reshape.png)

You can transpose your array with `arr.transpose()`. :

In [ ]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

You can also use `data.T`:

In [ ]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

![image](img/np_transposing_reshaping.png)

```{admonition} Question
Is the following code going to work? Why, or why not?
```

In [ ]:
data.reshape((3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

```{admonition} Answer
:class: tip dropdown
No, because `data` has a shape `(3, 2)`, so `3 * 2 = 6` elements, while the shape `(3, 3)` would require `3 * 3 = 9` elements
```

## Broadcasting

There are times when you might want to carry out an operation between an
array and a single number (also called *an operation between a vector
and a scalar*) or between arrays of two different sizes. For example,
your array (we'll call it "data") might contain information about
distance in miles but you want to convert the information to kilometers.
You can perform this operation with:

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![image](img/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell.
That concept is called **broadcasting**. Broadcasting is a mechanism
that allows NumPy to perform operations on arrays of different shapes.
The dimensions of your array must be compatible, for example, when the
dimensions of both arrays are equal or when one of them is 1. If the
dimensions are not compatible, you will get a `ValueError`.


This works with scalars, but not only! For matrices, you can do these arithmetic operations on matrices of different sizes,
but only if one matrix has only one column or one row. In this case,
NumPy will use its broadcast rules for the operation. :

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![image](img/np_matrix_broadcasting.png)

```{admonition} Question
What would be the result of the following sum?
```

In [ ]:
range_col = np.arange(3).reshape((3, 1))
data + range_col

array([[1, 2],
       [4, 5],
       [7, 8]])

## Selecting part of an array 

### By index

You can index and slice NumPy arrays in the same ways you can slice
Python lists. :

In [32]:
data = np.array([1, 2, 3])
data[1]

2

In [33]:
data[0:2]

array([1, 2])

In [34]:
data[1:]

array([2, 3])

In [35]:
data[-2:]

array([2, 3])

You can visualize it this way:

![image](img/np_indexing.png)

You may want to take a section of your array or specific array elements
to use in further analysis or additional operations. To do that, you'll
need to subset, slice, and/or index your arrays.

Same goes in more than one dimension, you may specify an index or slice along each dimension.

In [94]:
data = np.array([[1, 2], [3, 4], [5, 6]])

Like for instance, to select a single element:

In [96]:
data[0, 1]

(2,
 array([[3, 4],
        [5, 6]]),
 array([1, 3]))

Slicing over the rows only:

In [98]:
data[1:3]

array([[3, 4],
       [5, 6]])

Or taking a single column, and a slice of rows:

In [97]:
data[0:2, 0]

array([1, 3])

![image](img/np_matrix_indexing.png)

### By array of indices

You may also provide arrays of indices to select from:

In [103]:
data[np.array([1, 2])]

array([[3, 4],
       [5, 6]])

```{admonition} Question
Since `data[1:3]` is equivalent to `data[1:3, 0:2]`, what would you expect the following to return?
```

In [106]:
data[np.arange(1, 3), np.arange(0, 2)]

array([3, 6])

Probably not what you expected, uh? Why so? To answer that, let's see what happens if we write what we'd naively think the equivalent of `data[0:3, 0:2]` to be:

In [114]:
data[np.arange(0, 3), np.arange(0, 2)]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (1,2) 

This does not just have an unexpected behaviour, it doesn't even work! But what's the problem? Inspecting the error, we see that the source of the problem is a broadcasting error. And when can a broadcasting error come up? This is a hard one but you may have guessed it: when we... try to broadcast.

In fact, NumPy first takes the two arrays we pass it, and tries to broadcast them to a common shape, as can for instance be done successfully for the two following arrays:

In [128]:
rows = np.arange(1, 3)
cols = np.array([[0, 1], [0, 1]])
np.broadcast_arrays(rows, cols)

[array([[1, 2],
        [1, 2]]),
 array([[0, 1],
        [0, 1]])]

Then, since they are broadcastable, the following does work:

In [127]:
data[rows, cols]

array([[3, 6],
       [3, 6]])

As you can see, the result has the same shape as each output of the broadcasting. So, actually, in each broadcasted input, each element corresponds to the index to select from `data` along the dimension they represent. So for instance, the top left element will be taken from the second row (index=1) and the first column (index=0). 

```{admonition} Question
So what happened when we ran `data[np.arange(1, 3), np.arange(0, 2)]` above?
```

```{admonition} Answer
:class: tip dropdown
This is a simpler example than what we just saw: here the broadcasting doesn't do anything, since the two input arrays have the same shape, equal to `(2,)`. So this just created an array of shape `(2,)`, in which the first element is taken from `data[1, 0]` (= 3), and the second from `data[2, 1]` (= 6).
```

### By condition

If you want to select values from your array that fulfill certain
conditions, it's straightforward with NumPy.

For example, if you start with this array:

In [36]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than
5:

In [37]:
a[a < 5]

array([1, 2, 3, 4])

You can also select, for example, numbers that are equal to or greater
than 5, and use that condition to index an array. :

In [38]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

The variable `five_up` is what is known as a *boolean mask*: you can use it to mask part of an array to select only part of it, but also to modify part of it!

You can also select elements that satisfy two conditions using the `&` and
`|` operators:

In [39]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

You can also make use of the logical operators **&** and **\|** in order
to return boolean values that specify whether or not the values in an
array fulfill a certain condition. This can be useful with arrays that
contain names or other categorical values. :

In [40]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

You can also use `np.nonzero()` to select elements or indices from an
array.

Starting with this array:

In [41]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can use `np.nonzero()` to print the indices of elements that are,
for example, less than 5:

In [42]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In this example, a tuple of arrays was returned: one for each dimension.
The first array represents the row indices where these values are found,
and the second array represents the column indices where the values are
found.

If you want to generate a list of coordinates where the elements exist,
you can zip the arrays, iterate over the list of coordinates, and print
them. For example:

In [43]:
list_of_coordinates = list(zip(b[0], b[1]))
for row, col in list_of_coordinates:
    print((row, col))

(0, 0)
(0, 1)
(0, 2)
(0, 3)


You can also use `np.nonzero()` to print the elements in an array that
are less than 5 with:

In [44]:
print(a[b])

[1 2 3 4]


If the element you're looking for doesn't exist in the array, then the
returned array of indices will be empty. For example:

In [45]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


**Exercise**: modify the arrays `floored1` and `floored2` so that their minimum value is 5, in two ways:
- using a boolean mask directly
- using `np.nonzero()`

In [46]:
floored1 = a.copy()
floored2 = a.copy()

In [47]:
floored1[floored1 < 5] = 5
floored1

array([[ 5,  5,  5,  5],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
floored2[np.nonzero(floored2 < 5)] = 5
floored2

array([[ 5,  5,  5,  5],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Array aggregation

NumPy also performs aggregation functions, such as `min`, `max`, `sum`, `mean` to get the average, `prod` to get
the result of multiplying the elements together, `std` to get the
standard deviation, and more. :

In [212]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [133]:
data.max(), data.min(), data.sum()

(6, 1, 21)

![](img/np_matrix_aggregation.png)

As you can see, by default, every NumPy aggregation function will return the aggregate of the entire array. But it's very common to want to aggregate along a row or column. For that, you need to say explicitly over which `axis` you wish your aggregation to run.

For instance, you can get the maxmimum over the axis of rows with:

In [216]:
data.max(axis=0)

array([5, 6])

You can get it over the axis of columns with:

In [217]:
data.max(axis=1)

array([2, 5, 6])

![image](img/np_matrix_aggregation_row.png)

## Working with mathematical formulas

The ease of implementing mathematical formulas that work on arrays is
one of the things that make NumPy so widely used in the scientific
Python community.

For example, this is the mean square error formula (a central formula
used in supervised machine learning models that deal with regression):

![image](img/np_MSE_formula.png)

Implementing this formula is simple and straightforward in NumPy:

![image](img/np_MSE_implementation.png)

What makes this work so well is that `predictions` and `labels` can
contain one or a thousand values. They only need to be the same size.

You can visualize it this way:

![image](img/np_mse_viz1.png)

In this example, both the predictions and labels vectors contain three
values, meaning `n` has a value of three. After we carry out
subtractions the values in the vector are squared. Then NumPy sums the
values, and your result is the error value for that prediction and a
score for the quality of the model.

![image](img/np_mse_viz2.png)

![image](img/np_MSE_explanation2.png)

## NaNs and infinites

Some operations may lead to situations that are not mathematically defined, or that yield infinite results. Let's have a brief overview of these two situations. 

### NaNs

A NaN is Not a Number, that you can get from NumPy simply as:

In [74]:
np.nan

nan

But it is actually considered a float:

In [75]:
type(np.nan)

float

So it's a float number that is not a number, and more interesting even, that's not equal to itself:

In [77]:
np.nan == np.nan

False

In reality, `np.nan` is not equal to _anything_, and further, any test that involves it on one side or the other of the test will return `False`. So for instance, as shown below, it is neither positive, nor negative or equal to 0:

In [78]:
not (np.nan > 0) and not (np.nan < 0) and not (np.nan == 0)

True

Further, (almost) any operation involving it will return `np.nan` as well:

In [80]:
0 * np.nan

nan

But so, what's the point of having this number? To answer that, let's talk a bit about maths.

In maths, some functions are not defined for a certain range of values. For instance, the logarithm `log(x)` has the following behaviour:

* $x < 0$: not defined 
* $x = 0$: tends to minus infinity 
* $x > 0$: defined

![log function](img/log.png)

So to define a `log` function in NumPy, what do we do when users pass values that are inferior to 0? One option could have been to raise an error. But if one single negative value is passed in a large array, this would discard the whole result of some computations. So, instead, the [standard defining floating point numbers](https://en.wikipedia.org/wiki/IEEE_754#NaNs) created this particular float to represent an undefined result. Therefore, the `log` function in NumPy returns `nan` when passed a negative number:

In [84]:
np.log([-1, 2, 3])

/tmp/ipykernel_296202/2474035747.py:1: RuntimeWarning: invalid value encountered in log
  np.log([-1, 2, 3])


array([       nan, 0.69314718, 1.09861229])

and raises a warning, instead of an error. Thankfully, a special function `np.isnan()` is provided to detect their presence:

In [87]:
np.isnan(np.log([-1, 2, 3]))

/tmp/ipykernel_296202/1668739231.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log([-1, 2, 3]))


array([ True, False, False])

### Infinite

More straightforward are infinite numbers. Since they are infinitely large, it's not safe to represent the infinite by an arbitrarily large number, so, instead, a special floating-point number is used to represent it:

In [85]:
np.log(0)

/tmp/ipykernel_296202/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

Which, similarly to `nan`, can be identified with:

In [86]:
np.isinf(np.log([0, 1, 2]))

/tmp/ipykernel_296202/1630574277.py:1: RuntimeWarning: divide by zero encountered in log
  np.isinf(np.log([0, 1, 2]))


array([ True, False, False])

### What to do with them?

So, given an array which might have values leading to these behaviours, what do we do? Suppose we have the following example array:

In [91]:
arr = np.array([-1, 0, 1, 2])

And a fucntion with some undefined domain, like `log`.

Either you filter the array passed to `np.log()`, ensuring that whatever you pass it is within the range of values for which the function is properly defined:

In [92]:
np.log(arr[arr > 0])

array([0.        , 0.69314718])

Or you filter values a posteriori:

In [93]:
res = np.log(arr)
res[~np.isnan(res) & (~np.isinf(res))]

/tmp/ipykernel_296202/3078605770.py:1: RuntimeWarning: divide by zero encountered in log
  res = np.log(arr)
/tmp/ipykernel_296202/3078605770.py:1: RuntimeWarning: invalid value encountered in log
  res = np.log(arr)


array([0.        , 0.69314718])

Note that in this example, the latter is more cumbersome. However, sometimes you might get an array with NaNs from another source, or they might be used to represent missing data, so it's good to be able to handle them.

## How to save and load NumPy objects


You will, at some point, want to save your arrays to disk and load them
back without having to re-run the code. Fortunately, there are several
ways to save and load objects with NumPy. The ndarray objects can be
saved to and loaded from the disk files with `loadtxt` and `savetxt`
functions that handle normal text files, `load` and `save` functions
that handle NumPy binary files with a **.npy** file extension, and a
`savez` function that handles NumPy files with a **.npz** file
extension.

```{note}
The **.npy** and **.npz** files store data, shape, dtype, and other
information required to reconstruct the ndarray in a way that allows the
array to be correctly retrieved, even when the file is on another
machine with different architecture.
```

Here, we will only cover `loadtxt` and `savetxt` though, as they'll also allow us to refresh your memory on reading and writing text files.

You can save a NumPy array as a plain text file like a **.csv** or
**.txt** file with `np.savetxt`.

For example, if you create this array:

In [130]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can easily save it as a .csv file with the name "new_file.csv" like
this:

In [131]:
np.savetxt('new_file.csv', csv_arr)

You can quickly and easily load your saved text file using `loadtxt()`:

In [ ]:
np.loadtxt('new_file.csv')

The ``savetxt()`` and ``loadtxt()`` functions accept additional optional
parameters such as header, footer, and delimiter.